pipeline {
  agent {
    docker {
      image 'magicsong/porter-infra:v0.0.1'
      args '-v /var/run/docker.sock:/var/run/docker.sock  -v /usr/bin/docker:/usr/bin/docker -v /tmp:/tmp --net=host -v gomod-porter:/go'
    }
  }
  environment {
    tag = sh(
      script: 'git rev-parse --short HEAD',
      returnStdout: true
    ).trim()
    JENKINS_IP = '192.168.98.8'
    KUBECONFIG = "/root/.kube/config"
  }
  stages {
    stage('Set up kubeconfig and secret'){
     steps{
        sh 'mkdir -p ~/.kube'
        withCredentials([kubeconfigContent(credentialsId: 'lbkubeconfig', variable: 'KUBECONFIG_CONTENT')]) {
           sh 'echo "$KUBECONFIG_CONTENT" > ~/.kube/config'
        }
      }
    }
    stage('Building Manager'){
      steps{
        sh """
            ./hack/deploy.sh kubespheredev/porter:$tag manager
        """
      }
    }
    stage('Building Agent'){
      steps{
        sh """
            ./hack/deploy.sh kubespheredev/porter-agent:$tag agent
        """
      }
    }
    stage('Testing') {
      steps {
        sh """
            make e2e-nobuild
          """
      }
    }
  }
  post {
        always {
            sh """
              docker rmi kubespheredev/porter:$tag
              docker rmi kubespheredev/porter-agent:$tag
            """
        }
        failure{
            archiveArtifacts artifacts: 'test/*.porterlog', fingerprint: true
        }
    }
}