pipeline {
  agent {
    docker {
      image 'kubespheredev/porter-infra:0.0.1'
      args '-v $HOME:/root -v /var/run/docker.sock:/var/run/docker.sock  -v /usr/bin/docker:/usr/bin/docker -v /tmp:/tmp --net=host'
    }
  }
  environment {
    tag = sh(
      script: 'git rev-parse --short HEAD',
      returnStdout: true
    ).trim()
    JENKINS_IP = '192.168.98.8'
  }
  stages {
    stage('Prepare'){
      steps{
        echo "PATH is: $PATH"
        sh """
            mkdir -p /go/src/github.com/kubesphere
            ln -s `pwd` /go/src/github.com/kubesphere/porter
        """
      }
    }
    stage('Building Manager'){
      steps{
        sh """
            cd /go/src/github.com/kubesphere/porter
            ./hack/deploy.sh kubespheredev/porter:$tag manager
        """
      }
    }
    stage('Building Agent'){
      steps{
        sh """
            cd /go/src/github.com/kubesphere/porter
            ./hack/deploy.sh kubespheredev/porter-agent:$tag agent
        """
      }
    }
    stage('Test') {
      steps {
        sh """
            cd /go/src/github.com/kubesphere/porter
            make e2e-nobuild
          """
      }
    }
  }
  post {
        always {
            echo 'Clean images'
            try {
              archiveArtifacts artifacts: 'deploy/*.yaml', fingerprint: true
              archiveArtifacts artifacts: 'test/*.porterlog', fingerprint: true
              sh """
                docker rmi kubespheredev/porter:$tag
                docker rmi kubespheredev/porter-agent:$tag
              """
            } catch (err){
              echo err
            }
        }
    }
}