---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openelb-speaker
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openelb-speaker
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - nodes
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - network.kubesphere.io
  resources:
  - bgpconfs
  - bgppeers
  - eips
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.kubesphere.io
  resources:
  - bgpconfs/finalizers
  verbs:
  - update
- apiGroups:
  - network.kubesphere.io
  resources:
  - bgppeers/status
  - eips/status
  - bgpconfs/status
  verbs:
  - get
  - patch
  - update

# openelb-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openelb-controller
rules:
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases/status
  verbs:
    - get
    - update
    - patch
- apiGroups:
    - apps
  resources:
    - daemonsets
    - deployments
  verbs:
    - create
    - delete
    - patch
    - update


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openelb-controller
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - nodes
  - pods
  - pods/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - services/status
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.kubesphere.io
  resources:
  - eips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.kubesphere.io
  resources:
  - eips/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - get
  - list
  - watch
